Dark Mode Switch Button Added
hashirshoaeb/star_book pull request #77
Opened 2021-01-07 15:07 UTC by KhyatiSaini

Fixes issue #60 
Added the switch button in the PreferenceSheet for dark mode (UI)

2021-01-07 15:21 UTC, hashirshoaeb requested changes
Remove custom switch library and life and use CupertinoSlidingSegmentedControl in Cupertino package

2021-01-07 18:56 UTC, KhyatiSaini commented
![WhatsApp Image 2021-01-08 at 00 13 23](https://user-images.githubusercontent.com/55757584/103932556-06e38000-5148-11eb-8161-6a37be7cf979.jpeg)

2021-01-08 02:44 UTC, hashirshoaeb reviewed
I'm doing some refactoring.

2021-01-08 02:46 UTC, hashirshoaeb approved these changes

2021-01-08 02:47 UTC, merged